import { AvataaarType } from "./types";

export const AvatarStyleOptions = ['Circle', 'Transparent'] as const;
export const TopTypeOptions = [
    'NoHair',
    'Eyepatch',
    'Hat',
    'Hijab',
    'LongHairBigHair',
    'LongHairBob',
    'LongHairBun',
    'LongHairCurly',
    'LongHairCurvy',
    'LongHairDreads',
    'LongHairFrida',
    'LongHairFro',
    'LongHairFroBand',
    'LongHairMiaWallace',
    'LongHairNotTooLong',
    'LongHairShavedSides',
    'LongHairStraight',
    'LongHairStraight2',
    'LongHairStraightStrand',
    'ShortHairDreads01',
    'ShortHairDreads02',
    'ShortHairFrizzle',
    'ShortHairShaggyMullet',
    'ShortHairShortCurly',
    'ShortHairShortFlat',
    'ShortHairShortRound',
    'ShortHairShortWaved',
    'ShortHairSides',
    'ShortHairTheCaesar',
    'ShortHairTheCaesarSidePart',
    'Turban',
    'WinterHat1',
    'WinterHat2',
    'WinterHat3',
    'WinterHat4',
  ] as const;
  export const AccessoriesTypeOptions = ['Blank', 'Kurt', 'Prescription01', 'Prescription02', 'Round', 'Sunglasses', 'Wayfarers'] as const;
  export const HatColorOptions = [
    'Black',
    'Blue01',
    'Blue02',
    'Blue03',
    'Gray01',
    'Gray02',
    'Heather',
    'PastelBlue',
    'PastelGreen',
    'PastelOrange',
    'PastelRed',
    'PastelYellow',
    'Pink',
    'Red',
    'White',
  ] as const;
  export const HairColorOptions = [
    'Auburn',
    'Black',
    'Blonde',
    'BlondeGolden',
    'Brown',
    'BrownDark',
    'PastelPink',
    'Blue',
    'Platinum',
    'Red',
    'SilverGray',
  ] as const;
  export const FacialHairTypeOptions = [
    'Blank',
    'BeardLight',
    'BeardMajestic',
    'BeardMedium',
    'MoustacheFancy',
    'MoustacheMagnum',
  ] as const;
  export const FacialHairColorOptions = ['Auburn', 'Black', 'Blonde', 'BlondeGolden', 'Brown', 'BrownDark', 'Platinum', 'Red', 'SilverGray'] as const;
  export const ClotheTypeOptions =  [
    'BlazerShirt',
    'BlazerSweater',
    'CollarSweater',
    'GraphicShirt',
    'Hoodie',
    'Overall',
    'ShirtCrewNeck',
    'ShirtScoopNeck',
    'ShirtVNeck',
  ] as const;
  export const ClotheColorOptions = [
    'Black',
    'Blue01',
    'Blue02',
    'Blue03',
    'Gray01',
    'Gray02',
    'Heather',
    'PastelBlue',
    'PastelGreen',
    'PastelOrange',
    'PastelRed',
    'PastelYellow',
    'Pink',
    'Red',
    'White',
  ] as const;
  export const GraphicTypeOptions = [
    'Bat',
    'Cumbia',
    'Deer',
    'Diamond',
    'Hola',
    'Pizza',
    'Resist',
    'Selena',
    'Bear',
    'SkullOutline',
    'Skull',
  ] as const;
  export const EyeTypeOptions = [
    'Close',
    'Cry',
    'Default',
    'Dizzy',
    'EyeRoll',
    'Happy',
    'Hearts',
    'Side',
    'Squint',
    'Surprised',
    'Wink',
    'WinkWacky',
  ] as const;
  export const EyebrowTypeOptions = [
    'Angry',
    'AngryNatural',
    'Default',
    'DefaultNatural',
    'FlatNatural',
    'FrownNatural',
    'RaisedExcited',
    'RaisedExcitedNatural',
    'SadConcerned',
    'SadConcernedNatural',
    'UnibrowNatural',
    'UpDown',
    'UpDownNatural',
  ] as const;
  export const MouthTypeOptions = [
    'Concerned',
    'Default',
    'Disbelief',
    'Eating',
    'Grimace',
    'Sad',
    'ScreamOpen',
    'Serious',
    'Smile',
    'Tongue',
    'Twinkle',
    'Vomit',
  ] as const;
  export const SkinColorOptions = ['Tanned', 'Yellow', 'Pale', 'Light', 'Brown', 'DarkBrown', 'Black'] as const;

export const AvataaarOptions = {
  accessoriesType: AccessoriesTypeOptions,
  avatarStyle: AvatarStyleOptions,
  clotheColor: ClotheColorOptions,
  clotheType: ClotheTypeOptions,
  eyebrowType: EyebrowTypeOptions,
  eyeType: EyeTypeOptions,
  facialHairColor: FacialHairColorOptions,
  facialHairType: FacialHairTypeOptions,
  graphicType: GraphicTypeOptions,
  hairColor: HairColorOptions,
  hatColor: HatColorOptions,
  mouthType: MouthTypeOptions,
  skinColor: SkinColorOptions,
  topType: TopTypeOptions,
};

export const AvataaarDefaults: AvataaarType = {
  accessoriesType: 'Blank',
  avatarStyle: 'Transparent',
  clotheColor: 'Gray02',
  clotheType: 'BlazerShirt',
  eyebrowType: 'Default',
  eyeType: 'Default',
  facialHairColor: 'Brown',
  facialHairType: 'Blank',
  graphicType: 'Bear',
  hairColor: 'Brown',
  hatColor: 'Black',
  mouthType: 'Default',
  skinColor: 'Tanned',
  topType: 'ShortHairShortWaved',
};
